#!/usr/bin/env python3
"""Sichere, deterministische Datei- und Hash-Hilfsfunktionen.

Provenienz:
- Hash-/SOURCE_DATE_EPOCH-Muster: H234598/ADHS-Lernpfad,
  Commit 93c8c02d263ec123c1c271caf0d2deaa76760ccb.
- Atomare ``.part``-/``os.replace``-Muster: H234598/desinfect,
  Commit fbcc6e850fec1f4592ca519fa3e5141b11a95e60.
"""

from __future__ import annotations

from contextlib import contextmanager
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import shutil
import tempfile
from typing import Any, Iterator

BUILD_SENTINEL = ".cheatsheets-build-root"
DEFAULT_CHUNK_SIZE = 1024 * 1024


class UnsafePathError(ValueError):
    """Ein Pfad verlässt einen ausdrücklich erlaubten Wurzelpfad."""


def ensure_within(path: Path, root: Path) -> Path:
    """Löse *path* auf und stelle sicher, dass er unter *root* liegt."""

    resolved_root = root.resolve()
    resolved = path.resolve(strict=False)
    try:
        resolved.relative_to(resolved_root)
    except ValueError as exc:
        raise UnsafePathError(
            f"Pfad liegt außerhalb des erlaubten Wurzelpfads: {path}"
        ) from exc
    return resolved


def sha256_file(path: Path, chunk_size: int = DEFAULT_CHUNK_SIZE) -> str:
    """Berechne SHA-256 gestreamt, ohne die ganze Datei zu laden."""

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(chunk_size):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def stable_json_dumps(payload: Any, *, indent: int = 2) -> str:
    """Serialisiere JSON stabil, UTF-8-freundlich und mit abschließender Newline."""

    return (
        json.dumps(
            payload,
            ensure_ascii=False,
            indent=indent,
            sort_keys=True,
            separators=(",", ": "),
        )
        + "\n"
    )


def atomic_write_bytes(path: Path, payload: bytes) -> None:
    """Schreibe eine Datei atomar über eine benachbarte ``.part``-Datei."""

    path.parent.mkdir(parents=True, exist_ok=True)
    part = path.with_name(f".{path.name}.{os.getpid()}.part")
    try:
        with part.open("wb") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(part, path)
    finally:
        part.unlink(missing_ok=True)


def atomic_write_text(path: Path, text: str) -> None:
    atomic_write_bytes(path, text.encode("utf-8"))


def mark_generated_root(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    atomic_write_text(path / BUILD_SENTINEL, "generated by cheatsheets build\n")


def assert_generated_root(path: Path) -> None:
    if not (path / BUILD_SENTINEL).is_file():
        raise UnsafePathError(
            f"Generiertes Ziel ist nicht durch {BUILD_SENTINEL} markiert: {path}"
        )


def safe_remove_generated_tree(path: Path, allowed_root: Path) -> None:
    ensure_within(path, allowed_root)
    assert_generated_root(path)
    shutil.rmtree(path)


@contextmanager
def staged_directory(
    target: Path,
    *,
    allowed_root: Path,
    force: bool = False,
) -> Iterator[Path]:
    """Erzeuge ein Staging-Verzeichnis und tausche es nach Erfolg atomar aus.

    Das vorhandene Ziel wird nur ersetzt, wenn es als generierter Buildroot
    markiert ist. Bei einem Fehler bleibt das vorherige vollständige Ziel
    erhalten.
    """

    target = ensure_within(target, allowed_root)
    allowed_root.mkdir(parents=True, exist_ok=True)
    staging = Path(
        tempfile.mkdtemp(prefix=f".{target.name}.staging-", dir=allowed_root)
    )
    mark_generated_root(staging)
    backup = allowed_root / f".{target.name}.backup-{os.getpid()}"

    try:
        yield staging
        if target.exists():
            assert_generated_root(target)
            if backup.exists():
                assert_generated_root(backup)
                shutil.rmtree(backup)
            os.replace(target, backup)
        os.replace(staging, target)
        if backup.exists():
            shutil.rmtree(backup)
    except Exception:
        if target.exists() and backup.exists():
            # Ziel wurde bereits ersetzt; den alten vollständigen Stand retten.
            assert_generated_root(target)
            shutil.rmtree(target)
            os.replace(backup, target)
        elif not target.exists() and backup.exists():
            os.replace(backup, target)
        raise
    finally:
        if staging.exists():
            shutil.rmtree(staging)
        if backup.exists() and force:
            assert_generated_root(backup)
            shutil.rmtree(backup)


def source_date_epoch() -> int:
    """Liefere den reproduzierbaren Buildzeitpunkt oder ``0`` als Fallback."""

    raw = os.environ.get("SOURCE_DATE_EPOCH", "0").strip()
    try:
        value = int(raw)
    except ValueError as exc:
        raise ValueError("SOURCE_DATE_EPOCH muss eine ganze Zahl sein") from exc
    if value < 0:
        raise ValueError("SOURCE_DATE_EPOCH darf nicht negativ sein")
    return value


def generated_at_iso() -> str:
    return datetime.fromtimestamp(source_date_epoch(), tz=timezone.utc).isoformat().replace(
        "+00:00", "Z"
    )
